### ISSUE TITLE
Calculation of Alignment and Uniformity

### ISSUE THREAD

**Issue by fstermann** [SAP-samples/acl2022-self-contrastive-decorrelation#13]
Hi, thank you for the interesting paper.
Im trying to calculate the alignment and uniformity metrics you provided in the paper, and need some clarification on how you came to your results.

Could you specify on which STS task you calculated these metrics? I saw that you added a custom evaluation in `sts_filter.py`, but there only the `STSFilterBenchmarkEval` is really used. Does that mean that the metrics are only calculated on this task? Also, you add the alignment and uniformity together over the train, dev and test set [here](https://github.com/SAP-samples/acl2022-self-contrastive-decorrelation/blob/main/SentEval/senteval/sts_filter.py#L125). Is the correct way of going about this, or should this actually be calculated over the combined dataset, like the spearman correlation which is used for reference?

Could you maybe provide the source code used to calculate the metrics?

**Comment by TJKlein** [comment]
Unfortunately, it is quite a long time ago, so I only remember some of the evaluation details of this specific experiment. Yes, the analysis is conducted on the averaged STS results (just it is done in papers like [SimCSE](https://arxiv.org/pdf/2104.08821.pdf)). I don't see a problem with using train+test data for this experiment since the model is trained on random Wikipedia sentences.
